package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ChargeOutRate generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "ChargeOutRate", uniqueConstraints = @UniqueConstraint(columnNames = "grade"))
public class ChargeOutRate implements java.io.Serializable {

	@Id
	private String grade;
	private BigDecimal rate;
	private BigDecimal overtimeRate;
	private Date createDate;
	private String createBy;
	private Date updDate;
	private String updBy;

	public ChargeOutRate() {
	}

	public ChargeOutRate(String grade, BigDecimal rate, Date createDate,
			String createBy) {
		this.grade = grade;
		this.rate = rate;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public ChargeOutRate(String grade, BigDecimal rate,
			BigDecimal overtimeRate, Date createDate, String createBy,
			Date updDate, String updBy) {
		this.grade = grade;
		this.rate = rate;
		this.overtimeRate = overtimeRate;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updDate = updDate;
		this.updBy = updBy;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public BigDecimal getOvertimeRate() {
		return this.overtimeRate;
	}

	public void setOvertimeRate(BigDecimal overtimeRate) {
		this.overtimeRate = overtimeRate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	public String getUpdBy() {
		return this.updBy;
	}

	public void setUpdBy(String updBy) {
		this.updBy = updBy;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChargeOutRate))
			return false;
		ChargeOutRate castOther = (ChargeOutRate) other;

		return ((this.getGrade() == castOther.getGrade()) || (this.getGrade() != null
				&& castOther.getGrade() != null && this.getGrade().equals(
				castOther.getGrade())))
				&& ((this.getRate() == castOther.getRate()) || (this.getRate() != null
						&& castOther.getRate() != null && this.getRate()
						.equals(castOther.getRate())))
				&& ((this.getOvertimeRate() == castOther.getOvertimeRate()) || (this
						.getOvertimeRate() != null
						&& castOther.getOvertimeRate() != null && this
						.getOvertimeRate().equals(castOther.getOvertimeRate())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreateBy() == castOther.getCreateBy()) || (this
						.getCreateBy() != null
						&& castOther.getCreateBy() != null && this
						.getCreateBy().equals(castOther.getCreateBy())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())))
				&& ((this.getUpdBy() == castOther.getUpdBy()) || (this
						.getUpdBy() != null && castOther.getUpdBy() != null && this
						.getUpdBy().equals(castOther.getUpdBy())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGrade() == null ? 0 : this.getGrade().hashCode());
		result = 37 * result
				+ (getRate() == null ? 0 : this.getRate().hashCode());
		result = 37
				* result
				+ (getOvertimeRate() == null ? 0 : this.getOvertimeRate()
						.hashCode());
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37 * result
				+ (getCreateBy() == null ? 0 : this.getCreateBy().hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		result = 37 * result
				+ (getUpdBy() == null ? 0 : this.getUpdBy().hashCode());
		return result;
	}

}
