package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CostCenter generated by hbm2java
 */
public class CostCenter implements java.io.Serializable {

	private String costCenterId;
	private String costCenterName;
	private String costCenterDes;
	private String crtUser;
	private Date crtDate;
	private String updUser;
	private Date updDate;
	private String divisionId;

	public CostCenter() {
	}

	public CostCenter(String costCenterId, String costCenterName,
			String crtUser, String updUser) {
		this.costCenterId = costCenterId;
		this.costCenterName = costCenterName;
		this.crtUser = crtUser;
		this.updUser = updUser;
	}

	public CostCenter(String costCenterId, String costCenterName,
			String costCenterDes, String crtUser, Date crtDate, String updUser,
			Date updDate, String divisionId) {
		this.costCenterId = costCenterId;
		this.costCenterName = costCenterName;
		this.costCenterDes = costCenterDes;
		this.crtUser = crtUser;
		this.crtDate = crtDate;
		this.updUser = updUser;
		this.updDate = updDate;
		this.divisionId = divisionId;
	}

	public String getCostCenterId() {
		return this.costCenterId;
	}

	public void setCostCenterId(String costCenterId) {
		this.costCenterId = costCenterId;
	}

	public String getCostCenterName() {
		return this.costCenterName;
	}

	public void setCostCenterName(String costCenterName) {
		this.costCenterName = costCenterName;
	}

	public String getCostCenterDes() {
		return this.costCenterDes;
	}

	public void setCostCenterDes(String costCenterDes) {
		this.costCenterDes = costCenterDes;
	}

	public String getCrtUser() {
		return this.crtUser;
	}

	public void setCrtUser(String crtUser) {
		this.crtUser = crtUser;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	public String getUpdUser() {
		return this.updUser;
	}

	public void setUpdUser(String updUser) {
		this.updUser = updUser;
	}

	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	public String getDivisionId() {
		return this.divisionId;
	}

	public void setDivisionId(String divisionId) {
		this.divisionId = divisionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CostCenter))
			return false;
		CostCenter castOther = (CostCenter) other;

		return ((this.getCostCenterId() == castOther.getCostCenterId()) || (this
				.getCostCenterId() != null
				&& castOther.getCostCenterId() != null && this
				.getCostCenterId().equals(castOther.getCostCenterId())))
				&& ((this.getCostCenterName() == castOther.getCostCenterName()) || (this
						.getCostCenterName() != null
						&& castOther.getCostCenterName() != null && this
						.getCostCenterName().equals(
								castOther.getCostCenterName())))
				&& ((this.getCostCenterDes() == castOther.getCostCenterDes()) || (this
						.getCostCenterDes() != null
						&& castOther.getCostCenterDes() != null && this
						.getCostCenterDes()
						.equals(castOther.getCostCenterDes())))
				&& ((this.getCrtUser() == castOther.getCrtUser()) || (this
						.getCrtUser() != null && castOther.getCrtUser() != null && this
						.getCrtUser().equals(castOther.getCrtUser())))
				&& ((this.getCrtDate() == castOther.getCrtDate()) || (this
						.getCrtDate() != null && castOther.getCrtDate() != null && this
						.getCrtDate().equals(castOther.getCrtDate())))
				&& ((this.getUpdUser() == castOther.getUpdUser()) || (this
						.getUpdUser() != null && castOther.getUpdUser() != null && this
						.getUpdUser().equals(castOther.getUpdUser())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())))
				&& ((this.getDivisionId() == castOther.getDivisionId()) || (this
						.getDivisionId() != null
						&& castOther.getDivisionId() != null && this
						.getDivisionId().equals(castOther.getDivisionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCostCenterId() == null ? 0 : this.getCostCenterId()
						.hashCode());
		result = 37
				* result
				+ (getCostCenterName() == null ? 0 : this.getCostCenterName()
						.hashCode());
		result = 37
				* result
				+ (getCostCenterDes() == null ? 0 : this.getCostCenterDes()
						.hashCode());
		result = 37 * result
				+ (getCrtUser() == null ? 0 : this.getCrtUser().hashCode());
		result = 37 * result
				+ (getCrtDate() == null ? 0 : this.getCrtDate().hashCode());
		result = 37 * result
				+ (getUpdUser() == null ? 0 : this.getUpdUser().hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		result = 37
				* result
				+ (getDivisionId() == null ? 0 : this.getDivisionId()
						.hashCode());
		return result;
	}

}
