package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Couse generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "Couse", uniqueConstraints = @UniqueConstraint(columnNames = "couseName"))
public class Couse implements java.io.Serializable {

	@Id
	private String couseName;
	private String couseCategoryName;
	private String comments;
	private Date createDate;
	private String createBy;
	private Date updDate;
	private String updBy;
	private String effectiveRangeFrom;
	private String effectiveRangeTo;
	private String chargeableInd;
	private String couseGroupName;

	public Couse() {
	}

	public Couse(String couseName, String couseCategoryName, Date createDate,
			String createBy, String chargeableInd) {
		this.couseName = couseName;
		this.couseCategoryName = couseCategoryName;
		this.createDate = createDate;
		this.createBy = createBy;
		this.chargeableInd = chargeableInd;
	}

	public Couse(String couseName, String couseCategoryName, String comments,
			Date createDate, String createBy, Date updDate, String updBy,
			String effectiveRangeFrom, String effectiveRangeTo,
			String chargeableInd, String couseGroupName) {
		this.couseName = couseName;
		this.couseCategoryName = couseCategoryName;
		this.comments = comments;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updDate = updDate;
		this.updBy = updBy;
		this.effectiveRangeFrom = effectiveRangeFrom;
		this.effectiveRangeTo = effectiveRangeTo;
		this.chargeableInd = chargeableInd;
		this.couseGroupName = couseGroupName;
	}

	public String getCouseName() {
		return this.couseName;
	}

	public void setCouseName(String couseName) {
		this.couseName = couseName;
	}

	public String getCouseCategoryName() {
		return this.couseCategoryName;
	}

	public void setCouseCategoryName(String couseCategoryName) {
		this.couseCategoryName = couseCategoryName;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	public String getUpdBy() {
		return this.updBy;
	}

	public void setUpdBy(String updBy) {
		this.updBy = updBy;
	}

	public String getEffectiveRangeFrom() {
		return this.effectiveRangeFrom;
	}

	public void setEffectiveRangeFrom(String effectiveRangeFrom) {
		this.effectiveRangeFrom = effectiveRangeFrom;
	}

	public String getEffectiveRangeTo() {
		return this.effectiveRangeTo;
	}

	public void setEffectiveRangeTo(String effectiveRangeTo) {
		this.effectiveRangeTo = effectiveRangeTo;
	}

	public String getChargeableInd() {
		return this.chargeableInd;
	}

	public void setChargeableInd(String chargeableInd) {
		this.chargeableInd = chargeableInd;
	}

	public String getCouseGroupName() {
		return this.couseGroupName;
	}

	public void setCouseGroupName(String couseGroupName) {
		this.couseGroupName = couseGroupName;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Couse))
			return false;
		Couse castOther = (Couse) other;

		return ((this.getCouseName() == castOther.getCouseName()) || (this
				.getCouseName() != null && castOther.getCouseName() != null && this
				.getCouseName().equals(castOther.getCouseName())))
				&& ((this.getCouseCategoryName() == castOther
						.getCouseCategoryName()) || (this
						.getCouseCategoryName() != null
						&& castOther.getCouseCategoryName() != null && this
						.getCouseCategoryName().equals(
								castOther.getCouseCategoryName())))
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreateBy() == castOther.getCreateBy()) || (this
						.getCreateBy() != null
						&& castOther.getCreateBy() != null && this
						.getCreateBy().equals(castOther.getCreateBy())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())))
				&& ((this.getUpdBy() == castOther.getUpdBy()) || (this
						.getUpdBy() != null && castOther.getUpdBy() != null && this
						.getUpdBy().equals(castOther.getUpdBy())))
				&& ((this.getEffectiveRangeFrom() == castOther
						.getEffectiveRangeFrom()) || (this
						.getEffectiveRangeFrom() != null
						&& castOther.getEffectiveRangeFrom() != null && this
						.getEffectiveRangeFrom().equals(
								castOther.getEffectiveRangeFrom())))
				&& ((this.getEffectiveRangeTo() == castOther
						.getEffectiveRangeTo()) || (this.getEffectiveRangeTo() != null
						&& castOther.getEffectiveRangeTo() != null && this
						.getEffectiveRangeTo().equals(
								castOther.getEffectiveRangeTo())))
				&& ((this.getChargeableInd() == castOther.getChargeableInd()) || (this
						.getChargeableInd() != null
						&& castOther.getChargeableInd() != null && this
						.getChargeableInd()
						.equals(castOther.getChargeableInd())))
				&& ((this.getCouseGroupName() == castOther.getCouseGroupName()) || (this
						.getCouseGroupName() != null
						&& castOther.getCouseGroupName() != null && this
						.getCouseGroupName().equals(
								castOther.getCouseGroupName())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCouseName() == null ? 0 : this.getCouseName().hashCode());
		result = 37
				* result
				+ (getCouseCategoryName() == null ? 0 : this
						.getCouseCategoryName().hashCode());
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37 * result
				+ (getCreateBy() == null ? 0 : this.getCreateBy().hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		result = 37 * result
				+ (getUpdBy() == null ? 0 : this.getUpdBy().hashCode());
		result = 37
				* result
				+ (getEffectiveRangeFrom() == null ? 0 : this
						.getEffectiveRangeFrom().hashCode());
		result = 37
				* result
				+ (getEffectiveRangeTo() == null ? 0 : this
						.getEffectiveRangeTo().hashCode());
		result = 37
				* result
				+ (getChargeableInd() == null ? 0 : this.getChargeableInd()
						.hashCode());
		result = 37
				* result
				+ (getCouseGroupName() == null ? 0 : this.getCouseGroupName()
						.hashCode());
		return result;
	}

}
