package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Division generated by hbm2java
 */
public class Division implements java.io.Serializable {

	private String divisionId;
	private String divisionName;
	private String crtUser;
	private Date crtDate;
	private String updUser;
	private Date updDate;

	public Division() {
	}

	public Division(String divisionId, String divisionName) {
		this.divisionId = divisionId;
		this.divisionName = divisionName;
	}

	public Division(String divisionId, String divisionName,
			String crtUser, Date crtDate, String updUser, Date updDate) {
		this.divisionId = divisionId;
		this.divisionName = divisionName;
		this.crtUser = crtUser;
		this.crtDate = crtDate;
		this.updUser = updUser;
		this.updDate = updDate;
	}

	public String getDivisionId() {
		return this.divisionId;
	}

	public void setDivisionId(String divisionId) {
		this.divisionId = divisionId;
	}

	public String getDivisionName() {
		return this.divisionName;
	}

	public void setDivisionName(String divisionName) {
		this.divisionName = divisionName;
	}

	public String getCrtUser() {
		return this.crtUser;
	}

	public void setCrtUser(String crtUser) {
		this.crtUser = crtUser;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	public String getUpdUser() {
		return this.updUser;
	}

	public void setUpdUser(String updUser) {
		this.updUser = updUser;
	}

	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Division))
			return false;
		Division castOther = (Division) other;

		return ((this.getDivisionId() == castOther.getDivisionId()) || (this
				.getDivisionId() != null && castOther.getDivisionId() != null && this
				.getDivisionId().equals(castOther.getDivisionId())))
				&& ((this.getDivisionName() == castOther.getDivisionName()) || (this
						.getDivisionName() != null
						&& castOther.getDivisionName() != null && this
						.getDivisionName().equals(castOther.getDivisionName())))
				&& ((this.getCrtUser() == castOther.getCrtUser()) || (this
						.getCrtUser() != null && castOther.getCrtUser() != null && this
						.getCrtUser().equals(castOther.getCrtUser())))
				&& ((this.getCrtDate() == castOther.getCrtDate()) || (this
						.getCrtDate() != null && castOther.getCrtDate() != null && this
						.getCrtDate().equals(castOther.getCrtDate())))
				&& ((this.getUpdUser() == castOther.getUpdUser()) || (this
						.getUpdUser() != null && castOther.getUpdUser() != null && this
						.getUpdUser().equals(castOther.getUpdUser())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDivisionId() == null ? 0 : this.getDivisionId()
						.hashCode());
		result = 37
				* result
				+ (getDivisionName() == null ? 0 : this.getDivisionName()
						.hashCode());
		result = 37 * result
				+ (getCrtUser() == null ? 0 : this.getCrtUser().hashCode());
		result = 37 * result
				+ (getCrtDate() == null ? 0 : this.getCrtDate().hashCode());
		result = 37 * result
				+ (getUpdUser() == null ? 0 : this.getUpdUser().hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		return result;
	}

}
