package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Func generated by hbm2java
 */
public class Func implements java.io.Serializable {

	private String funcId;
	private String funcName;
	private String parentId;
	private String url;
	private String division;
	private BigDecimal sequence;
	private String crtUser;
	private Date crtDate;
	private String updUser;
	private Date updDate;
	private String funcType;
	private Character isMenu;

	public Func() {
	}

	public Func(String funcId, String funcName) {
		this.funcId = funcId;
		this.funcName = funcName;
	}

	public Func(String funcId, String funcName, String parentId,
			String url, String division, BigDecimal sequence, String crtUser,
			Date crtDate, String updUser, Date updDate, String funcType,
			Character isMenu) {
		this.funcId = funcId;
		this.funcName = funcName;
		this.parentId = parentId;
		this.url = url;
		this.division = division;
		this.sequence = sequence;
		this.crtUser = crtUser;
		this.crtDate = crtDate;
		this.updUser = updUser;
		this.updDate = updDate;
		this.funcType = funcType;
		this.isMenu = isMenu;
	}

	public String getFuncId() {
		return this.funcId;
	}

	public void setFuncId(String funcId) {
		this.funcId = funcId;
	}

	public String getFuncName() {
		return this.funcName;
	}

	public void setFuncName(String funcName) {
		this.funcName = funcName;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public BigDecimal getSequence() {
		return this.sequence;
	}

	public void setSequence(BigDecimal sequence) {
		this.sequence = sequence;
	}

	public String getCrtUser() {
		return this.crtUser;
	}

	public void setCrtUser(String crtUser) {
		this.crtUser = crtUser;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	public String getUpdUser() {
		return this.updUser;
	}

	public void setUpdUser(String updUser) {
		this.updUser = updUser;
	}

	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	public String getFuncType() {
		return this.funcType;
	}

	public void setFuncType(String funcType) {
		this.funcType = funcType;
	}

	public Character getIsMenu() {
		return this.isMenu;
	}

	public void setIsMenu(Character isMenu) {
		this.isMenu = isMenu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Func))
			return false;
		Func castOther = (Func) other;

		return ((this.getFuncId() == castOther.getFuncId()) || (this
				.getFuncId() != null && castOther.getFuncId() != null && this
				.getFuncId().equals(castOther.getFuncId())))
				&& ((this.getFuncName() == castOther.getFuncName()) || (this
						.getFuncName() != null
						&& castOther.getFuncName() != null && this
						.getFuncName().equals(castOther.getFuncName())))
				&& ((this.getParentId() == castOther.getParentId()) || (this
						.getParentId() != null
						&& castOther.getParentId() != null && this
						.getParentId().equals(castOther.getParentId())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())))
				&& ((this.getDivision() == castOther.getDivision()) || (this
						.getDivision() != null
						&& castOther.getDivision() != null && this
						.getDivision().equals(castOther.getDivision())))
				&& ((this.getSequence() == castOther.getSequence()) || (this
						.getSequence() != null
						&& castOther.getSequence() != null && this
						.getSequence().equals(castOther.getSequence())))
				&& ((this.getCrtUser() == castOther.getCrtUser()) || (this
						.getCrtUser() != null && castOther.getCrtUser() != null && this
						.getCrtUser().equals(castOther.getCrtUser())))
				&& ((this.getCrtDate() == castOther.getCrtDate()) || (this
						.getCrtDate() != null && castOther.getCrtDate() != null && this
						.getCrtDate().equals(castOther.getCrtDate())))
				&& ((this.getUpdUser() == castOther.getUpdUser()) || (this
						.getUpdUser() != null && castOther.getUpdUser() != null && this
						.getUpdUser().equals(castOther.getUpdUser())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())))
				&& ((this.getFuncType() == castOther.getFuncType()) || (this
						.getFuncType() != null
						&& castOther.getFuncType() != null && this
						.getFuncType().equals(castOther.getFuncType())))
				&& ((this.getIsMenu() == castOther.getIsMenu()) || (this
						.getIsMenu() != null && castOther.getIsMenu() != null && this
						.getIsMenu().equals(castOther.getIsMenu())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFuncId() == null ? 0 : this.getFuncId().hashCode());
		result = 37 * result
				+ (getFuncName() == null ? 0 : this.getFuncName().hashCode());
		result = 37 * result
				+ (getParentId() == null ? 0 : this.getParentId().hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result
				+ (getDivision() == null ? 0 : this.getDivision().hashCode());
		result = 37 * result
				+ (getSequence() == null ? 0 : this.getSequence().hashCode());
		result = 37 * result
				+ (getCrtUser() == null ? 0 : this.getCrtUser().hashCode());
		result = 37 * result
				+ (getCrtDate() == null ? 0 : this.getCrtDate().hashCode());
		result = 37 * result
				+ (getUpdUser() == null ? 0 : this.getUpdUser().hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		result = 37 * result
				+ (getFuncType() == null ? 0 : this.getFuncType().hashCode());
		result = 37 * result
				+ (getIsMenu() == null ? 0 : this.getIsMenu().hashCode());
		return result;
	}

}
