package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FuncParameter generated by hbm2java
 */
public class FuncParameter implements java.io.Serializable {

	private String paramName;
	private String paramType;
	private String defaultValue;
	private String paramDesc;
	private String crtUser;
	private Date crtDate;
	private String updUser;
	private Date updDate;
	private BigDecimal seq;
	private String cssClass;
	private char isInput;

	public FuncParameter() {
	}

	public FuncParameter(String paramName, String paramType, String crtUser,
			String updUser, BigDecimal seq, char isInput) {
		this.paramName = paramName;
		this.paramType = paramType;
		this.crtUser = crtUser;
		this.updUser = updUser;
		this.seq = seq;
		this.isInput = isInput;
	}

	public FuncParameter(String paramName, String paramType,
			String defaultValue, String paramDesc, String crtUser,
			Date crtDate, String updUser, Date updDate, BigDecimal seq,
			String cssClass, char isInput) {
		this.paramName = paramName;
		this.paramType = paramType;
		this.defaultValue = defaultValue;
		this.paramDesc = paramDesc;
		this.crtUser = crtUser;
		this.crtDate = crtDate;
		this.updUser = updUser;
		this.updDate = updDate;
		this.seq = seq;
		this.cssClass = cssClass;
		this.isInput = isInput;
	}

	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public String getParamType() {
		return this.paramType;
	}

	public void setParamType(String paramType) {
		this.paramType = paramType;
	}

	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public String getParamDesc() {
		return this.paramDesc;
	}

	public void setParamDesc(String paramDesc) {
		this.paramDesc = paramDesc;
	}

	public String getCrtUser() {
		return this.crtUser;
	}

	public void setCrtUser(String crtUser) {
		this.crtUser = crtUser;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	public String getUpdUser() {
		return this.updUser;
	}

	public void setUpdUser(String updUser) {
		this.updUser = updUser;
	}

	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	public BigDecimal getSeq() {
		return this.seq;
	}

	public void setSeq(BigDecimal seq) {
		this.seq = seq;
	}

	public String getCssClass() {
		return this.cssClass;
	}

	public void setCssClass(String cssClass) {
		this.cssClass = cssClass;
	}

	public char getIsInput() {
		return this.isInput;
	}

	public void setIsInput(char isInput) {
		this.isInput = isInput;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FuncParameter))
			return false;
		FuncParameter castOther = (FuncParameter) other;

		return ((this.getParamName() == castOther.getParamName()) || (this
				.getParamName() != null && castOther.getParamName() != null && this
				.getParamName().equals(castOther.getParamName())))
				&& ((this.getParamType() == castOther.getParamType()) || (this
						.getParamType() != null
						&& castOther.getParamType() != null && this
						.getParamType().equals(castOther.getParamType())))
				&& ((this.getDefaultValue() == castOther.getDefaultValue()) || (this
						.getDefaultValue() != null
						&& castOther.getDefaultValue() != null && this
						.getDefaultValue().equals(castOther.getDefaultValue())))
				&& ((this.getParamDesc() == castOther.getParamDesc()) || (this
						.getParamDesc() != null
						&& castOther.getParamDesc() != null && this
						.getParamDesc().equals(castOther.getParamDesc())))
				&& ((this.getCrtUser() == castOther.getCrtUser()) || (this
						.getCrtUser() != null && castOther.getCrtUser() != null && this
						.getCrtUser().equals(castOther.getCrtUser())))
				&& ((this.getCrtDate() == castOther.getCrtDate()) || (this
						.getCrtDate() != null && castOther.getCrtDate() != null && this
						.getCrtDate().equals(castOther.getCrtDate())))
				&& ((this.getUpdUser() == castOther.getUpdUser()) || (this
						.getUpdUser() != null && castOther.getUpdUser() != null && this
						.getUpdUser().equals(castOther.getUpdUser())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())))
				&& ((this.getSeq() == castOther.getSeq()) || (this.getSeq() != null
						&& castOther.getSeq() != null && this.getSeq().equals(
						castOther.getSeq())))
				&& ((this.getCssClass() == castOther.getCssClass()) || (this
						.getCssClass() != null
						&& castOther.getCssClass() != null && this
						.getCssClass().equals(castOther.getCssClass())))
				&& (this.getIsInput() == castOther.getIsInput());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getParamName() == null ? 0 : this.getParamName().hashCode());
		result = 37 * result
				+ (getParamType() == null ? 0 : this.getParamType().hashCode());
		result = 37
				* result
				+ (getDefaultValue() == null ? 0 : this.getDefaultValue()
						.hashCode());
		result = 37 * result
				+ (getParamDesc() == null ? 0 : this.getParamDesc().hashCode());
		result = 37 * result
				+ (getCrtUser() == null ? 0 : this.getCrtUser().hashCode());
		result = 37 * result
				+ (getCrtDate() == null ? 0 : this.getCrtDate().hashCode());
		result = 37 * result
				+ (getUpdUser() == null ? 0 : this.getUpdUser().hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		result = 37 * result
				+ (getSeq() == null ? 0 : this.getSeq().hashCode());
		result = 37 * result
				+ (getCssClass() == null ? 0 : this.getCssClass().hashCode());
		result = 37 * result + this.getIsInput();
		return result;
	}

}
