package org.jboss.as.quickstart.hibernate4.model;

//package org.jboss.as.quickstart.hibernate4.model;
//
//// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1
//
//import java.util.Date;
//
///**
// * Group generated by hbm2java
// */
//public class Group implements java.io.Serializable {
//
//	private String groupName;
//	private String comments;
//	private Date createDate;
//	private String createBy;
//	private Date updDate;
//	private String updBy;
//
//	public Group() {
//	}
//
//	public Group(String groupName, Date createDate, String createBy) {
//		this.groupName = groupName;
//		this.createDate = createDate;
//		this.createBy = createBy;
//	}
//
//	public Group(String groupName, String comments, Date createDate,
//			String createBy, Date updDate, String updBy) {
//		this.groupName = groupName;
//		this.comments = comments;
//		this.createDate = createDate;
//		this.createBy = createBy;
//		this.updDate = updDate;
//		this.updBy = updBy;
//	}
//
//	public String getGroupName() {
//		return this.groupName;
//	}
//
//	public void setGroupName(String groupName) {
//		this.groupName = groupName;
//	}
//
//	public String getComments() {
//		return this.comments;
//	}
//
//	public void setComments(String comments) {
//		this.comments = comments;
//	}
//
//	public Date getCreateDate() {
//		return this.createDate;
//	}
//
//	public void setCreateDate(Date createDate) {
//		this.createDate = createDate;
//	}
//
//	public String getCreateBy() {
//		return this.createBy;
//	}
//
//	public void setCreateBy(String createBy) {
//		this.createBy = createBy;
//	}
//
//	public Date getUpdDate() {
//		return this.updDate;
//	}
//
//	public void setUpdDate(Date updDate) {
//		this.updDate = updDate;
//	}
//
//	public String getUpdBy() {
//		return this.updBy;
//	}
//
//	public void setUpdBy(String updBy) {
//		this.updBy = updBy;
//	}
//
//	@Override
//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof Group))
//			return false;
//		Group castOther = (Group) other;
//
//		return ((this.getGroupName() == castOther.getGroupName()) || (this
//				.getGroupName() != null && castOther.getGroupName() != null && this
//				.getGroupName().equals(castOther.getGroupName())))
//				&& ((this.getComments() == castOther.getComments()) || (this
//						.getComments() != null
//						&& castOther.getComments() != null && this
//						.getComments().equals(castOther.getComments())))
//				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
//						.getCreateDate() != null
//						&& castOther.getCreateDate() != null && this
//						.getCreateDate().equals(castOther.getCreateDate())))
//				&& ((this.getCreateBy() == castOther.getCreateBy()) || (this
//						.getCreateBy() != null
//						&& castOther.getCreateBy() != null && this
//						.getCreateBy().equals(castOther.getCreateBy())))
//				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
//						.getUpdDate() != null && castOther.getUpdDate() != null && this
//						.getUpdDate().equals(castOther.getUpdDate())))
//				&& ((this.getUpdBy() == castOther.getUpdBy()) || (this
//						.getUpdBy() != null && castOther.getUpdBy() != null && this
//						.getUpdBy().equals(castOther.getUpdBy())));
//	}
//
//	@Override
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result
//				+ (getGroupName() == null ? 0 : this.getGroupName().hashCode());
//		result = 37 * result
//				+ (getComments() == null ? 0 : this.getComments().hashCode());
//		result = 37
//				* result
//				+ (getCreateDate() == null ? 0 : this.getCreateDate()
//						.hashCode());
//		result = 37 * result
//				+ (getCreateBy() == null ? 0 : this.getCreateBy().hashCode());
//		result = 37 * result
//				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
//		result = 37 * result
//				+ (getUpdBy() == null ? 0 : this.getUpdBy().hashCode());
//		return result;
//	}
//
//}

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * @ClassName: Group.java
 * 
 * @Description: 用户组
 * 
 * @author GERRARD
 * 
 * @date 2015年1月26日下午2:22:24
 * 
 */
@Entity
@Table(name = "groupA")
public class Group implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8694664905284095892L;

	/**
	 * 主键ID
	 */
	private String pid;

	/**
	 * 组名
	 */
	private String groupName;

	// @MapsId("name")
	// , parameters = @Parameter(name = "property", value = "name")
	// @GenericGenerator(name = "generator", strategy = "foreign")
	// @GeneratedValue(generator = "generator")

	// private Group parentGroup;
	//
	@ManyToOne(targetEntity = Group.class)
	@JoinColumn(name = "parentGroupId", referencedColumnName = "pid", updatable = false, insertable = false)
	@Column(name = "parentGroupId", updatable = false, insertable = false)
	private String parentGroupId;

	public void setParentGroupId(String tmp) {
		this.parentGroupId = tmp;
	}

	public String getParentGroupId() {
		return this.parentGroupId;
	}

	private Set<Group> childGroup;

	public Group() {
	}

	public Group(String pid, String groupName, Group parentGroup,
			Set<Group> childGroup) {
		this.pid = pid;
		this.groupName = groupName;
		// this.parentGroup = parentGroup;
		this.childGroup = childGroup;
	}

	@Id
	@Column(name = "pid", unique = true, nullable = false, length = 32)
	@GeneratedValue(generator = "generator")
	@GenericGenerator(name = "generator", strategy = "uuid")
	public String getPid() {
		return pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	@Column(name = "group_name", length = 64)
	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	// public Group getParentGroup() {
	// return parentGroup;
	// }
	//
	// public void setParentGroup(Group parentGroup) {
	// this.parentGroup = parentGroup;
	// }

	@OneToMany(mappedBy = "parentGroupId", cascade = CascadeType.ALL)
	public Set<Group> getChildGroup() {
		return childGroup;
	}

	public void setChildGroup(Set<Group> childGroup) {
		this.childGroup = childGroup;
	}

}