package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * InstructorCouse generated by hbm2java
 */
public class InstructorCouse implements java.io.Serializable {

	private String couseName;
	private String instructorId;

	public InstructorCouse() {
	}

	public InstructorCouse(String couseName, String instructorId) {
		this.couseName = couseName;
		this.instructorId = instructorId;
	}

	public String getCouseName() {
		return this.couseName;
	}

	public void setCouseName(String couseName) {
		this.couseName = couseName;
	}

	public String getInstructorId() {
		return this.instructorId;
	}

	public void setInstructorId(String instructorId) {
		this.instructorId = instructorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InstructorCouse))
			return false;
		InstructorCouse castOther = (InstructorCouse) other;

		return ((this.getCouseName() == castOther.getCouseName()) || (this
				.getCouseName() != null && castOther.getCouseName() != null && this
				.getCouseName().equals(castOther.getCouseName())))
				&& ((this.getInstructorId() == castOther.getInstructorId()) || (this
						.getInstructorId() != null
						&& castOther.getInstructorId() != null && this
						.getInstructorId().equals(castOther.getInstructorId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCouseName() == null ? 0 : this.getCouseName().hashCode());
		result = 37
				* result
				+ (getInstructorId() == null ? 0 : this.getInstructorId()
						.hashCode());
		return result;
	}

}
