package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Lookup generated by hbm2java
 */
public class Lookup implements java.io.Serializable {

	private BigDecimal lookupid;
	private String fieldType;
	private String fieldName;
	private String fieldValue;
	private BigDecimal priority;
	private Date createDate;
	private String createBy;
	private String updBy;
	private Date lastUpdDate;

	public Lookup() {
	}

	public Lookup(BigDecimal lookupid, String fieldType,
			String fieldName, String fieldValue, BigDecimal priority,
			Date createDate, String createBy, String updBy, Date lastUpdDate) {
		this.lookupid = lookupid;
		this.fieldType = fieldType;
		this.fieldName = fieldName;
		this.fieldValue = fieldValue;
		this.priority = priority;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updBy = updBy;
		this.lastUpdDate = lastUpdDate;
	}

	public BigDecimal getLookupid() {
		return this.lookupid;
	}

	public void setLookupid(BigDecimal lookupid) {
		this.lookupid = lookupid;
	}

	public String getFieldType() {
		return this.fieldType;
	}

	public void setFieldType(String fieldType) {
		this.fieldType = fieldType;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getFieldValue() {
		return this.fieldValue;
	}

	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}

	public BigDecimal getPriority() {
		return this.priority;
	}

	public void setPriority(BigDecimal priority) {
		this.priority = priority;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getUpdBy() {
		return this.updBy;
	}

	public void setUpdBy(String updBy) {
		this.updBy = updBy;
	}

	public Date getLastUpdDate() {
		return this.lastUpdDate;
	}

	public void setLastUpdDate(Date lastUpdDate) {
		this.lastUpdDate = lastUpdDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Lookup))
			return false;
		Lookup castOther = (Lookup) other;

		return ((this.getLookupid() == castOther.getLookupid()) || (this
				.getLookupid() != null && castOther.getLookupid() != null && this
				.getLookupid().equals(castOther.getLookupid())))
				&& ((this.getFieldType() == castOther.getFieldType()) || (this
						.getFieldType() != null
						&& castOther.getFieldType() != null && this
						.getFieldType().equals(castOther.getFieldType())))
				&& ((this.getFieldName() == castOther.getFieldName()) || (this
						.getFieldName() != null
						&& castOther.getFieldName() != null && this
						.getFieldName().equals(castOther.getFieldName())))
				&& ((this.getFieldValue() == castOther.getFieldValue()) || (this
						.getFieldValue() != null
						&& castOther.getFieldValue() != null && this
						.getFieldValue().equals(castOther.getFieldValue())))
				&& ((this.getPriority() == castOther.getPriority()) || (this
						.getPriority() != null
						&& castOther.getPriority() != null && this
						.getPriority().equals(castOther.getPriority())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreateBy() == castOther.getCreateBy()) || (this
						.getCreateBy() != null
						&& castOther.getCreateBy() != null && this
						.getCreateBy().equals(castOther.getCreateBy())))
				&& ((this.getUpdBy() == castOther.getUpdBy()) || (this
						.getUpdBy() != null && castOther.getUpdBy() != null && this
						.getUpdBy().equals(castOther.getUpdBy())))
				&& ((this.getLastUpdDate() == castOther.getLastUpdDate()) || (this
						.getLastUpdDate() != null
						&& castOther.getLastUpdDate() != null && this
						.getLastUpdDate().equals(castOther.getLastUpdDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLookupid() == null ? 0 : this.getLookupid().hashCode());
		result = 37 * result
				+ (getFieldType() == null ? 0 : this.getFieldType().hashCode());
		result = 37 * result
				+ (getFieldName() == null ? 0 : this.getFieldName().hashCode());
		result = 37
				* result
				+ (getFieldValue() == null ? 0 : this.getFieldValue()
						.hashCode());
		result = 37 * result
				+ (getPriority() == null ? 0 : this.getPriority().hashCode());
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37 * result
				+ (getCreateBy() == null ? 0 : this.getCreateBy().hashCode());
		result = 37 * result
				+ (getUpdBy() == null ? 0 : this.getUpdBy().hashCode());
		result = 37
				* result
				+ (getLastUpdDate() == null ? 0 : this.getLastUpdDate()
						.hashCode());
		return result;
	}

}
