package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PasswdHistory generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "PasswdHistory", uniqueConstraints = @UniqueConstraint(columnNames = "userId"))
public class PasswdHistory implements java.io.Serializable {

	@Id
	private String userId;
	private String passwd;
	private Date effDate;

	public PasswdHistory() {
	}

	public PasswdHistory(Date effDate) {
		this.effDate = effDate;
	}

	public PasswdHistory(String userId, String passwd, Date effDate) {
		this.userId = userId;
		this.passwd = passwd;
		this.effDate = effDate;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public Date getEffDate() {
		return this.effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PasswdHistory))
			return false;
		PasswdHistory castOther = (PasswdHistory) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getPasswd() == castOther.getPasswd()) || (this
						.getPasswd() != null && castOther.getPasswd() != null && this
						.getPasswd().equals(castOther.getPasswd())))
				&& ((this.getEffDate() == castOther.getEffDate()) || (this
						.getEffDate() != null && castOther.getEffDate() != null && this
						.getEffDate().equals(castOther.getEffDate())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getPasswd() == null ? 0 : this.getPasswd().hashCode());
		result = 37 * result
				+ (getEffDate() == null ? 0 : this.getEffDate().hashCode());
		return result;
	}

}
