package org.jboss.as.quickstart.hibernate4.model;


// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * Restrict generated by hbm2java
 */
// @Entity
// @XmlRootElement
// @Table(name = "Restrict", uniqueConstraints = @UniqueConstraint(columnNames =
// "name"))
public class Restrict implements java.io.Serializable {

	private short beforeQuantity;
	private short afterQuantity;
	private String unit;

	public Restrict() {
	}

	public Restrict(short beforeQuantity, short afterQuantity, String unit) {
		this.beforeQuantity = beforeQuantity;
		this.afterQuantity = afterQuantity;
		this.unit = unit;
	}

	public short getBeforeQuantity() {
		return this.beforeQuantity;
	}

	public void setBeforeQuantity(short beforeQuantity) {
		this.beforeQuantity = beforeQuantity;
	}

	public short getAfterQuantity() {
		return this.afterQuantity;
	}

	public void setAfterQuantity(short afterQuantity) {
		this.afterQuantity = afterQuantity;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Restrict))
			return false;
		Restrict castOther = (Restrict) other;

		return (this.getBeforeQuantity() == castOther.getBeforeQuantity())
				&& (this.getAfterQuantity() == castOther.getAfterQuantity())
				&& ((this.getUnit() == castOther.getUnit()) || (this.getUnit() != null
						&& castOther.getUnit() != null && this.getUnit()
						.equals(castOther.getUnit())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBeforeQuantity();
		result = 37 * result + this.getAfterQuantity();
		result = 37 * result
				+ (getUnit() == null ? 0 : this.getUnit().hashCode());
		return result;
	}

}
