package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Role generated by hbm2java
 */
// @Entity
// @XmlRootElement
// @Table(name = "Role2", uniqueConstraints = @UniqueConstraint(columnNames =
// "name"))
public class Role implements java.io.Serializable {

	private String roleId;
	private String roleName;
	private String roleDes;
	private String crtUser;
	private Date crtDate;
	private String updUser;
	private Date updDate;

	public Role() {
	}

	public Role(String roleId, String roleName, String crtUser, String updUser) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.crtUser = crtUser;
		this.updUser = updUser;
	}

	public Role(String roleId, String roleName, String roleDes, String crtUser,
			Date crtDate, String updUser, Date updDate) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDes = roleDes;
		this.crtUser = crtUser;
		this.crtDate = crtDate;
		this.updUser = updUser;
		this.updDate = updDate;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDes() {
		return this.roleDes;
	}

	public void setRoleDes(String roleDes) {
		this.roleDes = roleDes;
	}

	public String getCrtUser() {
		return this.crtUser;
	}

	public void setCrtUser(String crtUser) {
		this.crtUser = crtUser;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	public String getUpdUser() {
		return this.updUser;
	}

	public void setUpdUser(String updUser) {
		this.updUser = updUser;
	}

	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Role))
			return false;
		Role castOther = (Role) other;

		return ((this.getRoleId() == castOther.getRoleId()) || (this
				.getRoleId() != null && castOther.getRoleId() != null && this
				.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getRoleName() == castOther.getRoleName()) || (this
						.getRoleName() != null
						&& castOther.getRoleName() != null && this
						.getRoleName().equals(castOther.getRoleName())))
				&& ((this.getRoleDes() == castOther.getRoleDes()) || (this
						.getRoleDes() != null && castOther.getRoleDes() != null && this
						.getRoleDes().equals(castOther.getRoleDes())))
				&& ((this.getCrtUser() == castOther.getCrtUser()) || (this
						.getCrtUser() != null && castOther.getCrtUser() != null && this
						.getCrtUser().equals(castOther.getCrtUser())))
				&& ((this.getCrtDate() == castOther.getCrtDate()) || (this
						.getCrtDate() != null && castOther.getCrtDate() != null && this
						.getCrtDate().equals(castOther.getCrtDate())))
				&& ((this.getUpdUser() == castOther.getUpdUser()) || (this
						.getUpdUser() != null && castOther.getUpdUser() != null && this
						.getUpdUser().equals(castOther.getUpdUser())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result
				+ (getRoleName() == null ? 0 : this.getRoleName().hashCode());
		result = 37 * result
				+ (getRoleDes() == null ? 0 : this.getRoleDes().hashCode());
		result = 37 * result
				+ (getCrtUser() == null ? 0 : this.getCrtUser().hashCode());
		result = 37 * result
				+ (getCrtDate() == null ? 0 : this.getCrtDate().hashCode());
		result = 37 * result
				+ (getUpdUser() == null ? 0 : this.getUpdUser().hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		return result;
	}

}
