package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * SystemParameter generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "SystemParameter", uniqueConstraints = @UniqueConstraint(columnNames = "sysParamName"))
public class SystemParameter implements java.io.Serializable {

	@Id
	private String sysParamName;
	private String sysParamValue;
	private String sysParamDes;
	private String crtUser;
	private Date crtDate;
	private String updUser;
	private Date updDate;

	public SystemParameter() {
	}

	public SystemParameter(String sysParamName, String sysParamValue,
			String crtUser, String updUser) {
		this.sysParamName = sysParamName;
		this.sysParamValue = sysParamValue;
		this.crtUser = crtUser;
		this.updUser = updUser;
	}

	public SystemParameter(String sysParamName, String sysParamValue,
			String sysParamDes, String crtUser, Date crtDate, String updUser,
			Date updDate) {
		this.sysParamName = sysParamName;
		this.sysParamValue = sysParamValue;
		this.sysParamDes = sysParamDes;
		this.crtUser = crtUser;
		this.crtDate = crtDate;
		this.updUser = updUser;
		this.updDate = updDate;
	}

	public String getSysParamName() {
		return this.sysParamName;
	}

	public void setSysParamName(String sysParamName) {
		this.sysParamName = sysParamName;
	}

	public String getSysParamValue() {
		return this.sysParamValue;
	}

	public void setSysParamValue(String sysParamValue) {
		this.sysParamValue = sysParamValue;
	}

	public String getSysParamDes() {
		return this.sysParamDes;
	}

	public void setSysParamDes(String sysParamDes) {
		this.sysParamDes = sysParamDes;
	}

	public String getCrtUser() {
		return this.crtUser;
	}

	public void setCrtUser(String crtUser) {
		this.crtUser = crtUser;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	public String getUpdUser() {
		return this.updUser;
	}

	public void setUpdUser(String updUser) {
		this.updUser = updUser;
	}

	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SystemParameter))
			return false;
		SystemParameter castOther = (SystemParameter) other;

		return ((this.getSysParamName() == castOther.getSysParamName()) || (this
				.getSysParamName() != null
				&& castOther.getSysParamName() != null && this
				.getSysParamName().equals(castOther.getSysParamName())))
				&& ((this.getSysParamValue() == castOther.getSysParamValue()) || (this
						.getSysParamValue() != null
						&& castOther.getSysParamValue() != null && this
						.getSysParamValue()
						.equals(castOther.getSysParamValue())))
				&& ((this.getSysParamDes() == castOther.getSysParamDes()) || (this
						.getSysParamDes() != null
						&& castOther.getSysParamDes() != null && this
						.getSysParamDes().equals(castOther.getSysParamDes())))
				&& ((this.getCrtUser() == castOther.getCrtUser()) || (this
						.getCrtUser() != null && castOther.getCrtUser() != null && this
						.getCrtUser().equals(castOther.getCrtUser())))
				&& ((this.getCrtDate() == castOther.getCrtDate()) || (this
						.getCrtDate() != null && castOther.getCrtDate() != null && this
						.getCrtDate().equals(castOther.getCrtDate())))
				&& ((this.getUpdUser() == castOther.getUpdUser()) || (this
						.getUpdUser() != null && castOther.getUpdUser() != null && this
						.getUpdUser().equals(castOther.getUpdUser())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSysParamName() == null ? 0 : this.getSysParamName()
						.hashCode());
		result = 37
				* result
				+ (getSysParamValue() == null ? 0 : this.getSysParamValue()
						.hashCode());
		result = 37
				* result
				+ (getSysParamDes() == null ? 0 : this.getSysParamDes()
						.hashCode());
		result = 37 * result
				+ (getCrtUser() == null ? 0 : this.getCrtUser().hashCode());
		result = 37 * result
				+ (getCrtDate() == null ? 0 : this.getCrtDate().hashCode());
		result = 37 * result
				+ (getUpdUser() == null ? 0 : this.getUpdUser().hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		return result;
	}

}
