package org.jboss.as.quickstart.hibernate4.model;

// Generated Jan 16, 2015 11:33:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * User generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "User", uniqueConstraints = @UniqueConstraint(columnNames = "loginId"))
public class User implements java.io.Serializable {

	@Id
	private String loginId;
	private String userName;
	private String userDes;
	private String passwd;
	private Date passExpDate;
	private String roleId;
	private String costCenterId;
	private String email;
	private String mobile;
	private String userId;
	private String crtUser;
	private Date crtDate;
	private String updUser;
	private Date updDate;
	private Date inactiveDate;
	private String deactivatedBy;
	private Date deactivatedDate;
	private String companyCode;
	private boolean loginTrial;
	private String alias;

	public User() {
	}

	public User(String loginId, String userName, String passwd,
			String costCenterId, String userId, String crtUser, String updUser,
			boolean loginTrial) {
		this.loginId = loginId;
		this.userName = userName;
		this.passwd = passwd;
		this.costCenterId = costCenterId;
		this.userId = userId;
		this.crtUser = crtUser;
		this.updUser = updUser;
		this.loginTrial = loginTrial;
	}

	public User(String loginId, String userName, String userDes, String passwd,
			Date passExpDate, String roleId, String costCenterId, String email,
			String mobile, String userId, String crtUser, Date crtDate,
			String updUser, Date updDate, Date inactiveDate,
			String deactivatedBy, Date deactivatedDate, String companyCode,
			boolean loginTrial, String alias) {
		this.loginId = loginId;
		this.userName = userName;
		this.userDes = userDes;
		this.passwd = passwd;
		this.passExpDate = passExpDate;
		this.roleId = roleId;
		this.costCenterId = costCenterId;
		this.email = email;
		this.mobile = mobile;
		this.userId = userId;
		this.crtUser = crtUser;
		this.crtDate = crtDate;
		this.updUser = updUser;
		this.updDate = updDate;
		this.inactiveDate = inactiveDate;
		this.deactivatedBy = deactivatedBy;
		this.deactivatedDate = deactivatedDate;
		this.companyCode = companyCode;
		this.loginTrial = loginTrial;
		this.alias = alias;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserDes() {
		return this.userDes;
	}

	public void setUserDes(String userDes) {
		this.userDes = userDes;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public Date getPassExpDate() {
		return this.passExpDate;
	}

	public void setPassExpDate(Date passExpDate) {
		this.passExpDate = passExpDate;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getCostCenterId() {
		return this.costCenterId;
	}

	public void setCostCenterId(String costCenterId) {
		this.costCenterId = costCenterId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getCrtUser() {
		return this.crtUser;
	}

	public void setCrtUser(String crtUser) {
		this.crtUser = crtUser;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	public String getUpdUser() {
		return this.updUser;
	}

	public void setUpdUser(String updUser) {
		this.updUser = updUser;
	}

	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	public String getDeactivatedBy() {
		return this.deactivatedBy;
	}

	public void setDeactivatedBy(String deactivatedBy) {
		this.deactivatedBy = deactivatedBy;
	}

	public Date getDeactivatedDate() {
		return this.deactivatedDate;
	}

	public void setDeactivatedDate(Date deactivatedDate) {
		this.deactivatedDate = deactivatedDate;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public boolean isLoginTrial() {
		return this.loginTrial;
	}

	public void setLoginTrial(boolean loginTrial) {
		this.loginTrial = loginTrial;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof User))
			return false;
		User castOther = (User) other;

		return ((this.getLoginId() == castOther.getLoginId()) || (this
				.getLoginId() != null && castOther.getLoginId() != null && this
				.getLoginId().equals(castOther.getLoginId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserDes() == castOther.getUserDes()) || (this
						.getUserDes() != null && castOther.getUserDes() != null && this
						.getUserDes().equals(castOther.getUserDes())))
				&& ((this.getPasswd() == castOther.getPasswd()) || (this
						.getPasswd() != null && castOther.getPasswd() != null && this
						.getPasswd().equals(castOther.getPasswd())))
				&& ((this.getPassExpDate() == castOther.getPassExpDate()) || (this
						.getPassExpDate() != null
						&& castOther.getPassExpDate() != null && this
						.getPassExpDate().equals(castOther.getPassExpDate())))
				&& ((this.getRoleId() == castOther.getRoleId()) || (this
						.getRoleId() != null && castOther.getRoleId() != null && this
						.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getCostCenterId() == castOther.getCostCenterId()) || (this
						.getCostCenterId() != null
						&& castOther.getCostCenterId() != null && this
						.getCostCenterId().equals(castOther.getCostCenterId())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getMobile() == castOther.getMobile()) || (this
						.getMobile() != null && castOther.getMobile() != null && this
						.getMobile().equals(castOther.getMobile())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getCrtUser() == castOther.getCrtUser()) || (this
						.getCrtUser() != null && castOther.getCrtUser() != null && this
						.getCrtUser().equals(castOther.getCrtUser())))
				&& ((this.getCrtDate() == castOther.getCrtDate()) || (this
						.getCrtDate() != null && castOther.getCrtDate() != null && this
						.getCrtDate().equals(castOther.getCrtDate())))
				&& ((this.getUpdUser() == castOther.getUpdUser()) || (this
						.getUpdUser() != null && castOther.getUpdUser() != null && this
						.getUpdUser().equals(castOther.getUpdUser())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())))
				&& ((this.getInactiveDate() == castOther.getInactiveDate()) || (this
						.getInactiveDate() != null
						&& castOther.getInactiveDate() != null && this
						.getInactiveDate().equals(castOther.getInactiveDate())))
				&& ((this.getDeactivatedBy() == castOther.getDeactivatedBy()) || (this
						.getDeactivatedBy() != null
						&& castOther.getDeactivatedBy() != null && this
						.getDeactivatedBy()
						.equals(castOther.getDeactivatedBy())))
				&& ((this.getDeactivatedDate() == castOther
						.getDeactivatedDate()) || (this.getDeactivatedDate() != null
						&& castOther.getDeactivatedDate() != null && this
						.getDeactivatedDate().equals(
								castOther.getDeactivatedDate())))
				&& ((this.getCompanyCode() == castOther.getCompanyCode()) || (this
						.getCompanyCode() != null
						&& castOther.getCompanyCode() != null && this
						.getCompanyCode().equals(castOther.getCompanyCode())))
				&& (this.isLoginTrial() == castOther.isLoginTrial())
				&& ((this.getAlias() == castOther.getAlias()) || (this
						.getAlias() != null && castOther.getAlias() != null && this
						.getAlias().equals(castOther.getAlias())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLoginId() == null ? 0 : this.getLoginId().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getUserDes() == null ? 0 : this.getUserDes().hashCode());
		result = 37 * result
				+ (getPasswd() == null ? 0 : this.getPasswd().hashCode());
		result = 37
				* result
				+ (getPassExpDate() == null ? 0 : this.getPassExpDate()
						.hashCode());
		result = 37 * result
				+ (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37
				* result
				+ (getCostCenterId() == null ? 0 : this.getCostCenterId()
						.hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result
				+ (getMobile() == null ? 0 : this.getMobile().hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getCrtUser() == null ? 0 : this.getCrtUser().hashCode());
		result = 37 * result
				+ (getCrtDate() == null ? 0 : this.getCrtDate().hashCode());
		result = 37 * result
				+ (getUpdUser() == null ? 0 : this.getUpdUser().hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		result = 37
				* result
				+ (getInactiveDate() == null ? 0 : this.getInactiveDate()
						.hashCode());
		result = 37
				* result
				+ (getDeactivatedBy() == null ? 0 : this.getDeactivatedBy()
						.hashCode());
		result = 37
				* result
				+ (getDeactivatedDate() == null ? 0 : this.getDeactivatedDate()
						.hashCode());
		result = 37
				* result
				+ (getCompanyCode() == null ? 0 : this.getCompanyCode()
						.hashCode());
		result = 37 * result + (this.isLoginTrial() ? 1 : 0);
		result = 37 * result
				+ (getAlias() == null ? 0 : this.getAlias().hashCode());
		return result;
	}

}
